version: 2.1

jobs:
  e2e-tests:
    docker:
      - image: cimg/node:20.11.0
    
    steps:
      - checkout
      
      - run:
          name: Instalando dependências do sistema
          command: |
            sudo apt-get update
            sudo apt-get install -y libnspr4 libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0 libpango-1.0-0 libpangocairo-1.0-0
      
      - run:
          name: Instalando dependências
          command: yarn
      
      - run:
          name: Instalando Browsers do Playwright
          command: yarn playwright install
      
      - run:
          name: Executando testes e2e
          command: yarn run e2e
      
      - store_test_results:
          path: test-results
      
      - store_artifacts:
          path: playwright-report

workflows:
  version: 2
  e2e-tests-workflow:
    jobs:
      - e2e-tests
